db_path = "./db"
static_path = "./static"
port = 8080

# Secret mappings
mng_secret = "secret"
mng_get_papers_secret = "secret"
mng_approve_papers_secret = "secret"
mng_reject_papers_secret = "secret"
